name: full flow 3
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.output.outputs.test}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: cache deps
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Build code
        run: npm run build
      - name: get output
        id: output
        run: find dist/assets/**.js -type f -execdir echo 'test={}' >> $GITHUB_OUTPUT ';'
      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: cache deps
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Get build
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Get output
        run: echo 'output here ${{ needs.test.outputs.test }}'
      - name: Deploy
        run: echo "deploying..." |
            ls