name: job_outputs
on: push
jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.set-output.outputs.test}}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: build
        run: npm run build
      - name: set output
        id: set-output
        run: find dist/assets/*.js -type f -execdir echo 'test={}' >> $GITHUB_OUTPUT ';'
  get-output:
    runs-on: ubuntu-latest
    needs: set-output
    steps:
      - name: log output
        run: echo ${{needs.set-output.outputs.test}}